vim.cmd([[highlight clear]])

if vim.g.syntax_on then
  vim.cmd([[syntax reset]])
end

vim.g.colors_name = "forest"
vim.o.background = "dark"

local c = {
  bg = "#292c34",
  surface = "#30343d",
  elevated = "#373b44",
  active_line = "#374047",
  selection = "#414b51",
  border = "#41464f",

  fg = "#c7c2ae",
  fg_bright = "#dedbd0",
  muted = "#9b9b91",
  disabled = "#6e7475",
  comment = "#818786",
  invisible = "#555b61",

  red = "#d28e8c",
  green = "#a8c598",
  yellow = "#c5c57d",
  blue = "#8eb5ad",
  magenta = "#c49aaf",
  cyan = "#8fb7ae",
  orange = "#d2a277",
  function_name = "#adbb97",
  type_name = "#cebe95",

  search = "#4d5546",
  search_active = "#665a42",
  red_bg = "#49383d",
  green_bg = "#35443d",
  yellow_bg = "#494639",
  info_bg = "#354449",
}

local groups = {
  -- Editor UI
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg, bg = c.bg },
  FloatBorder = { fg = c.border, bg = c.bg },
  FloatTitle = { fg = c.green, bg = c.surface, bold = true },
  ColorColumn = { bg = c.surface },
  Cursor = { fg = c.bg, bg = c.fg_bright },
  lCursor = { fg = c.bg, bg = c.fg_bright },
  CursorIM = { fg = c.bg, bg = c.fg_bright },
  CursorColumn = { bg = c.active_line },
  CursorLine = { bg = c.active_line },
  CursorLineNr = { fg = c.muted, bg = c.active_line },
  LineNr = { fg = c.invisible, bg = c.bg },
  LineNrAbove = { fg = c.invisible, bg = c.bg },
  LineNrBelow = { fg = c.invisible, bg = c.bg },
  SignColumn = { fg = c.muted, bg = c.bg },
  FoldColumn = { fg = c.comment, bg = c.bg },
  Folded = { fg = c.comment, bg = c.surface, italic = true },
  NonText = { fg = c.invisible },
  SpecialKey = { fg = c.invisible },
  Whitespace = { fg = c.invisible },
  EndOfBuffer = { fg = c.bg, bg = c.bg },
  Visual = { bg = c.selection },
  VisualNOS = { bg = c.selection },
  Search = { fg = c.fg_bright, bg = c.search },
  IncSearch = { fg = c.bg, bg = c.orange },
  CurSearch = { fg = c.bg, bg = c.orange },
  Substitute = { fg = c.bg, bg = c.orange },
  MatchParen = { fg = c.fg_bright, bg = c.elevated, bold = true },
  Directory = { fg = c.blue },

  -- Windows and menus
  WinSeparator = { fg = c.border, bg = c.bg },
  StatusLine = { fg = c.muted, bg = c.bg },
  StatusLineNC = { fg = c.disabled, bg = c.bg },
  TabLine = { fg = c.muted, bg = c.surface },
  TabLineFill = { bg = c.surface },
  TabLineSel = { fg = c.fg_bright, bg = c.bg },
  WinBar = { fg = c.fg_bright, bg = c.bg },
  WinBarNC = { fg = c.muted, bg = c.bg },
  Pmenu = { fg = c.fg, bg = c.surface },
  PmenuSel = { fg = c.fg_bright, bg = c.elevated },
  PmenuKind = { fg = c.blue, bg = c.surface },
  PmenuKindSel = { fg = c.blue, bg = c.elevated },
  PmenuExtra = { fg = c.muted, bg = c.surface },
  PmenuExtraSel = { fg = c.muted, bg = c.elevated },
  PmenuSbar = { bg = c.surface },
  PmenuThumb = { bg = c.border },
  WildMenu = { fg = c.fg_bright, bg = c.elevated },
  QuickFixLine = { bg = c.selection },

  -- Messages and diagnostics
  ErrorMsg = { fg = c.red },
  WarningMsg = { fg = c.orange },
  MoreMsg = { fg = c.green },
  ModeMsg = { fg = c.blue },
  Question = { fg = c.green },
  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.orange },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.muted },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.orange, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.muted, undercurl = true },
  LspInlayHint = { fg = c.disabled, bg = "NONE"},
  LspReferenceText = { bg = c.info_bg },
  LspReferenceRead = { bg = c.info_bg },
  LspReferenceWrite = { bg = c.selection },

  -- Legacy syntax
  Comment = { fg = c.comment, italic = true },
  Constant = { fg = c.yellow },
  String = { fg = c.green },
  Character = { fg = c.green },
  Number = { fg = c.magenta },
  Boolean = { fg = c.magenta },
  Float = { fg = c.magenta },
  Identifier = { fg = c.fg },
  Function = { fg = c.function_name },
  Statement = { fg = c.red },
  Conditional = { fg = c.red },
  Repeat = { fg = c.red },
  Label = { fg = c.red },
  Operator = { fg = c.orange },
  Keyword = { fg = c.red },
  Exception = { fg = c.red },
  PreProc = { fg = c.red },
  Include = { fg = c.red },
  Define = { fg = c.red },
  Macro = { fg = c.red },
  PreCondit = { fg = c.red },
  Type = { fg = c.type_name },
  StorageClass = { fg = c.red },
  Structure = { fg = c.type_name },
  Typedef = { fg = c.type_name },
  Special = { fg = c.cyan },
  SpecialChar = { fg = c.orange },
  Tag = { fg = c.cyan },
  Delimiter = { fg = c.fg },
  SpecialComment = { fg = c.comment, italic = true },
  Debug = { fg = c.orange },
  Underlined = { fg = c.blue, underline = true },
  Ignore = { fg = c.disabled },
  Error = { fg = c.red, bg = c.red_bg },
  Todo = { fg = c.yellow, bg = c.yellow_bg, bold = true },
  Title = { fg = c.yellow, bold = true },

  -- Treesitter syntax
  ["@attribute"] = { fg = c.blue },
  ["@boolean"] = { fg = c.magenta },
  ["@comment"] = { fg = c.comment, italic = true },
  ["@comment.documentation"] = { fg = c.comment, italic = true },
  ["@constant"] = { fg = c.yellow },
  ["@constant.builtin"] = { fg = c.magenta },
  ["@constructor"] = { fg = c.type_name },
  ["@function"] = { fg = c.function_name },
  ["@function.builtin"] = { fg = c.function_name },
  ["@function.call"] = { fg = c.function_name },
  ["@function.method"] = { fg = c.function_name },
  ["@function.method.call"] = { fg = c.function_name },
  ["@keyword"] = { fg = c.red },
  ["@keyword.function"] = { fg = c.red },
  ["@keyword.operator"] = { fg = c.red },
  ["@label"] = { fg = c.red },
  ["@module"] = { fg = c.fg },
  ["@namespace"] = { fg = c.fg },
  ["@number"] = { fg = c.magenta },
  ["@operator"] = { fg = c.orange },
  ["@property"] = { fg = c.cyan },
  ["@punctuation"] = { fg = c.fg },
  ["@punctuation.bracket"] = { fg = c.fg },
  ["@punctuation.delimiter"] = { fg = c.fg },
  ["@punctuation.special"] = { fg = c.orange },
  ["@string"] = { fg = c.green },
  ["@string.escape"] = { fg = c.orange },
  ["@string.regexp"] = { fg = c.orange },
  ["@string.special"] = { fg = c.magenta },
  ["@string.special.symbol"] = { fg = c.cyan },
  ["@spell"] = { fg = c.fg, bg = c.bg },
  ["@tag"] = { fg = c.cyan },
  ["@tag.attribute"] = { fg = c.blue },
  ["@tag.delimiter"] = { fg = c.fg },
  ["@type"] = { fg = c.type_name },
  ["@type.builtin"] = { fg = c.type_name },
  ["@variable"] = { fg = c.fg },
  ["@variable.builtin"] = { fg = c.red },
  ["@variable.parameter"] = { fg = c.fg },

  -- LSP semantic tokens
  ["@lsp.type.class"] = { fg = c.type_name },
  ["@lsp.type.enum"] = { fg = c.type_name },
  ["@lsp.type.function"] = { fg = c.function_name },
  ["@lsp.type.interface"] = { fg = c.type_name },
  ["@lsp.type.method"] = { fg = c.function_name },
  ["@lsp.type.namespace"] = { fg = c.fg },
  ["@lsp.type.parameter"] = { fg = c.fg },
  ["@lsp.type.property"] = { fg = c.cyan },
  ["@lsp.type.struct"] = { fg = c.type_name },
  ["@lsp.type.type"] = { fg = c.type_name },
  ["@lsp.type.variable"] = { fg = c.fg },
  ["@lsp.typemod.variable.readonly"] = { fg = c.red },
  ["@lsp.typemod.function.definition"] = { fg = c.function_name },
  ["@lsp.typemod.method.definition"] = { fg = c.function_name },

  -- Markup
  ["@markup.heading"] = { fg = c.yellow, bold = true },
  ["@markup.italic"] = { fg = c.fg, italic = true },
  ["@markup.strong"] = { fg = c.fg_bright, bold = true },
  ["@markup.link"] = { fg = c.blue },
  ["@markup.link.label"] = { fg = c.blue },
  ["@markup.link.url"] = { fg = c.magenta, underline = true },
  ["@markup.list"] = { fg = c.orange },
  ["@markup.quote"] = { fg = c.comment, italic = true },
  ["@markup.raw"] = { fg = c.fg, bg = c.bg},

  -- Git and diff
  DiffAdd = { fg = c.green, bg = c.green_bg },
  DiffChange = { fg = c.yellow, bg = c.yellow_bg },
  DiffDelete = { fg = c.red, bg = c.red_bg },
  DiffText = { fg = c.fg_bright, bg = c.selection },
  Added = { fg = c.green },
  Changed = { fg = c.yellow },
  Removed = { fg = c.red },
  ["@diff.plus"] = { fg = c.green },
  ["@diff.delta"] = { fg = c.yellow },
  ["@diff.minus"] = { fg = c.red },

  -- Plugin integrations
  NeoTreeNormal = { fg = c.fg, bg = c.bg },
  NeoTreeNormalNC = { fg = c.fg, bg = c.bg },
  NeoTreeEndOfBuffer = { fg = c.bg, bg = c.bg },
  NeoTreeWinSeparator = { fg = c.bg, bg = c.bg },
  NeoTreeFileName = { fg = c.muted },
  NeoTreeDirectoryName = { fg = c.muted },
  NeoTreeDirectoryIcon = { fg = c.muted },
  NeoTreeGitUntracked = { fg = c.green },
  NeoTreeGitConflict = { fg = c.orange },
  NeoTreeCursorLine = { bg = c.elevated },
  IblIndent = { fg = c.border },
  IblScope = { fg = c.disabled },
  GrugFarResultsMatch = { fg = c.fg_bright, bg = c.search },
  GrugFarHelpHeader = { fg = c.fg_bright },
  GrugFarResultsActionMessage = { fg = c.fg_bright },
  GrugFarResultsPath = { bg = c.active_line },
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end

local terminal_colors = {
  "#292c34",
  "#d28e8c",
  "#a8c598",
  "#c5c57d",
  "#8eb5ad",
  "#c49aaf",
  "#8fb7ae",
  "#c7c2ae",
  "#6e7475",
  "#e09a98",
  "#b4d1a4",
  "#d2d289",
  "#9ac1b9",
  "#d0a6bb",
  "#9bc3ba",
  "#dedbd0",
}

for index, color in ipairs(terminal_colors) do
  vim.g["terminal_color_" .. index - 1] = color
end
