vim.cmd([[highlight clear]])

if vim.g.syntax_on then
  vim.cmd([[syntax reset]])
end

vim.g.colors_name = "zed-gruvbox"
vim.o.background = "dark"

local c = {
  -- bg = "#32302f",
  bg = "#3b3735",

  surface = "#3b3735",
  chrome = "#4c4642",
  element = "#494340",
  selected = "#5b524c",
  border = "#5b534d",

  fg = "#ebdbb2",
  fg_bright = "#fbf1c7",
  muted = "#c5b597",
  disabled = "#998b78",
  comment = "#a89984",
  doc = "#c6b697",
  invisible = "#928474",

  red = "#fb4833",
  green = "#b8bb25",
  yellow = "#fabd2e",
  blue = "#83a598",
  magenta = "#d3869b",
  cyan = "#8ec07c",
  orange = "#fe7f18",
  hint = "#8c957d",
  predictive = "#717363",
  neo_tree_bg = "#3b3735",

  active_line = "#393533",
  selection = "#454c48",
  search = "#525f59",
  search_active = "#64603d",
  document_write = "#58524b",

  red_bg = "#590a0f",
  green_bg = "#322b11",
  yellow_bg = "#572e10",
  info_bg = "#1e2321",
}

local groups = {
  -- Editor UI
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg_bright, bg = c.surface },
  FloatBorder = { fg = c.border, bg = c.surface },
  FloatTitle = { fg = c.green, bg = c.surface, bold = true },
  ColorColumn = { bg = c.surface },
  Cursor = { fg = c.bg, bg = c.blue },
  lCursor = { fg = c.bg, bg = c.blue },
  CursorIM = { fg = c.bg, bg = c.blue },
  CursorColumn = { bg = c.active_line },
  CursorLine = { bg = c.active_line },
  CursorLineNr = { fg = "#dedcd3", bg = c.active_line },
  LineNr = { fg = "#6e6b5e", bg = c.bg },
  LineNrAbove = { fg = "#6e6b5e", bg = c.bg },
  LineNrBelow = { fg = "#6e6b5e", bg = c.bg },
  SignColumn = { fg = c.muted, bg = c.bg },
  FoldColumn = { fg = c.comment, bg = c.bg },
  Folded = { fg = c.muted, bg = c.surface },
  NonText = { fg = c.invisible },
  SpecialKey = { fg = c.invisible },
  Whitespace = { fg = c.invisible },
  EndOfBuffer = { fg = c.bg, bg = c.bg },
  Visual = { bg = c.selection },
  VisualNOS = { bg = c.selection },
  Search = { fg = c.fg_bright, bg = c.search },
  IncSearch = { fg = c.fg_bright, bg = c.search_active },
  CurSearch = { fg = c.fg_bright, bg = c.search_active },
  Substitute = { fg = c.fg_bright, bg = c.search_active },
  MatchParen = { fg = c.fg_bright, bg = c.selected, bold = true },
  Directory = { fg = c.blue },

  -- Windows and menus
  WinSeparator = { fg = c.border, bg = c.bg },
  StatusLine = { fg = c.fg_bright, bg = c.chrome },
  StatusLineNC = { fg = c.muted, bg = c.surface },
  TabLine = { fg = c.muted, bg = c.surface },
  TabLineFill = { bg = c.surface },
  TabLineSel = { fg = c.fg_bright, bg = c.bg },
  WinBar = { fg = c.fg_bright, bg = c.bg },
  WinBarNC = { fg = c.muted, bg = c.surface },
  Pmenu = { fg = c.fg_bright, bg = c.surface },
  PmenuSel = { fg = c.fg_bright, bg = c.selected },
  PmenuKind = { fg = c.blue, bg = c.surface },
  PmenuKindSel = { fg = c.blue, bg = c.selected },
  PmenuExtra = { fg = c.muted, bg = c.surface },
  PmenuExtraSel = { fg = c.muted, bg = c.selected },
  PmenuSbar = { bg = c.element },
  PmenuThumb = { bg = c.blue },
  WildMenu = { fg = c.fg_bright, bg = c.selected },
  QuickFixLine = { bg = c.selection },

  -- Messages and diagnostics
  ErrorMsg = { fg = c.red },
  WarningMsg = { fg = c.yellow },
  MoreMsg = { fg = c.green },
  ModeMsg = { fg = c.blue },
  Question = { fg = c.green },
  DiagnosticError = { fg = c.red },
  DiagnosticWarn = { fg = c.yellow },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.hint },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.hint, undercurl = true },
  LspInlayHint = { fg = c.predictive, bg = c.green_bg, italic = true },
  LspReferenceText = { bg = c.search },
  LspReferenceRead = { bg = c.search },
  LspReferenceWrite = { bg = c.document_write },

  -- Legacy syntax
  Comment = { fg = c.comment },
  Constant = { fg = c.yellow },
  String = { fg = c.green },
  Character = { fg = c.green },
  Number = { fg = c.magenta },
  Boolean = { fg = c.magenta },
  Float = { fg = c.magenta },
  Identifier = { fg = c.fg },
  Function = { fg = c.red },
  Statement = { fg = c.fg },
  Conditional = { fg = c.red },
  Repeat = { fg = c.red },
  Label = { fg = c.blue },
  Operator = { fg = c.cyan },
  Keyword = { fg = c.fg },
  Exception = { fg = c.red },
  PreProc = { fg = c.red },
  Include = { fg = c.red },
  Define = { fg = c.red },
  Macro = { fg = c.red },
  PreCondit = { fg = c.red },
  Type = { fg = c.yellow },
  StorageClass = { fg = c.red },
  Structure = { fg = c.yellow },
  Typedef = { fg = c.yellow },
  Special = { fg = c.cyan },
  SpecialChar = { fg = c.doc },
  Tag = { fg = c.cyan },
  Delimiter = { fg = "#e5d5ad" },
  SpecialComment = { fg = c.doc },
  Debug = { fg = c.orange },
  Underlined = { fg = c.cyan, underline = true },
  Ignore = { fg = c.disabled },
  Error = { fg = c.red, bg = c.red_bg },
  Todo = { fg = c.yellow, bg = c.yellow_bg, bold = true },
  Title = { fg = c.green, bold = true },

  -- Treesitter syntax
  ["@attribute"] = { fg = c.blue },
  ["@boolean"] = { fg = c.magenta },
  ["@comment"] = { fg = c.comment },
  ["@comment.documentation"] = { fg = c.doc },
  ["@constant"] = { fg = c.yellow },
  ["@constructor"] = { fg = c.blue },
  ["@function"] = { fg = c.fg },
  ["@function.builtin"] = { fg = c.fg },
  ["@keyword"] = { fg = c.red },
  ["@label"] = { fg = c.blue },
  ["@module"] = { fg = c.fg },
  ["@namespace"] = { fg = c.blue },
  ["@number"] = { fg = c.magenta },
  ["@operator"] = { fg = c.fg },
  ["@property"] = { fg = c.fg },
  ["@punctuation"] = { fg = "#d5c4a1" },
  ["@punctuation.bracket"] = { fg = c.comment },
  ["@punctuation.delimiter"] = { fg = "#e5d5ad" },
  ["@punctuation.special"] = { fg = "#e5d5ad" },
  ["@string"] = { fg = c.green },
  ["@string.escape"] = { fg = c.doc },
  ["@string.regexp"] = { fg = c.orange },
  ["@string.special"] = { fg = c.magenta },
  ["@string.special.symbol"] = { fg = c.cyan },
  ["@tag"] = { fg = c.cyan },
  ["@tag.attribute"] = { fg = c.blue },
  ["@tag.delimiter"] = { fg = "#e5d5ad" },
  ["@type"] = { fg = c.yellow },
  ["@type.builtin"] = { fg = c.yellow },
  ["@variable"] = { fg = c.fg },
  ["@variable.builtin"] = { fg = c.fg },
  ["@variable.parameter"] = { fg = c.fg },

	["@lsp.typemod.variable.readonly.go"] 		= 	{ fg = c.magenta, bg = "NONE" },
	["@lsp.typemod.method.definition.go"] 		= 	{ fg = c.green, bg = "NONE" },
  ["@lsp.typemod.function.definition.go"] = { fg = c.green },

  -- Markup
  ["@markup.heading"] = { fg = c.green, bold = true },
  ["@markup.italic"] = { fg = c.blue, italic = true },
  ["@markup.strong"] = { fg = c.blue, bold = true },
  ["@markup.link"] = { fg = c.fg, italic = true },
  ["@markup.link.label"] = { fg = c.fg, underline = true },
  ["@markup.link.url"] = { fg = c.magenta, underline = true },
  ["@markup.list"] = { fg = c.fg },
  ["@markup.quote"] = { fg = c.blue },
  ["@markup.raw"] = { fg = c.blue },

  -- Git and diff
  DiffAdd = { fg = c.green, bg = c.green_bg },
  DiffChange = { fg = c.yellow, bg = c.yellow_bg },
  DiffDelete = { fg = c.red, bg = c.red_bg },
  DiffText = { fg = c.fg_bright, bg = c.selected },
  Added = { fg = c.green },
  Changed = { fg = c.yellow },
  Removed = { fg = c.red },
  ["@diff.plus"] = { fg = c.green },
  ["@diff.delta"] = { fg = c.yellow },
  ["@diff.minus"] = { fg = c.red },

  -- Existing plugin integrations
  NeoTreeNormal = { fg = c.fg, bg = c.neo_tree_bg },
  NeoTreeNormalNC = { fg = c.fg, bg = c.neo_tree_bg },
  NeoTreeEndOfBuffer = { fg = c.neo_tree_bg, bg = c.neo_tree_bg },
  NeoTreeWinSeparator = { fg = c.neo_tree_bg, bg = c.neo_tree_bg },
  NeoTreeGitUntracked = { fg = c.green },
  NeoTreeFileName = { fg = c.muted },
  NeoTreeDirectoryName = { fg = c.muted },
  NeoTreeDirectoryIcon = { fg = c.muted },
  NeoTreeGitConflict = { fg = c.yellow },
  NeoTreeCursorLine = { bg = c.active_line },
  GrugFarResultsMatch = { fg = c.fg_bright, bg = c.search },
  GrugFarHelpHeader = { fg = c.fg_bright },
  GrugFarResultsActionMessage = { fg = c.fg_bright },
  GrugFarResultsPath = { bg = c.active_line },
}

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end

local terminal_colors = {
  "#282828",
  "#cc241d",
  "#98971a",
  "#d79921",
  "#458588",
  "#b16286",
  "#689d6a",
  "#a89984",
  "#928374",
  "#fb4934",
  "#b8bb26",
  "#fabd2f",
  "#83a598",
  "#d3869b",
  "#8ec07c",
  "#fbf1c7",
}

for index, color in ipairs(terminal_colors) do
  vim.g["terminal_color_" .. index - 1] = color
end
